In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [2]:
df = pd.read_csv("CleanData.csv")
print(df.head())


   cough  fever  sore_throat  shortness_of_breath  head_ache  \
0      1      0            0                    0          0   
1      1      1            0                    0          0   
2      0      0            0                    0          0   
3      0      0            0                    0          0   
4      0      0            0                    0          0   

   age_60_and_above  gender  Abroad  Contact  No_activite  corona_result  
0                 0       1       1        0            0              0  
1                 0       1       0        0            1              0  
2                 0       1       0        0            1              1  
3                 0       1       0        0            1              1  
4                 0       1       0        0            1              1  


In [3]:
print(df.shape)
print(df.info())

(47998, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47998 entries, 0 to 47997
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   cough                47998 non-null  int64
 1   fever                47998 non-null  int64
 2   sore_throat          47998 non-null  int64
 3   shortness_of_breath  47998 non-null  int64
 4   head_ache            47998 non-null  int64
 5   age_60_and_above     47998 non-null  int64
 6   gender               47998 non-null  int64
 7   Abroad               47998 non-null  int64
 8   Contact              47998 non-null  int64
 9   No_activite          47998 non-null  int64
 10  corona_result        47998 non-null  int64
dtypes: int64(11)
memory usage: 4.0 MB
None


In [4]:
X = df.drop('corona_result',axis=1).values
Y = df['corona_result'].values

print(X.shape)
print(Y.shape)


(47998, 10)
(47998,)


In [6]:
print(X)
print(Y)

[[1 0 0 ... 1 0 0]
 [1 1 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]]
[0 0 1 ... 1 1 1]


In [ ]:
from sklearn.datasets import make_blobs

#x,y = make_blobs(n_samples=20, centers=2, n_features=2, random_state=0)
#print(x.shape)
#print(y)